# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-15 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_auto_20180315_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='profissionais',
            field=models.ManyToManyField(to='adm.Profissional'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='custo',
            field=models.FloatField(),
        ),
    ]
