# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-15 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_remove_projeto_profissionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='profissionais',
            field=models.ManyToManyField(to='adm.Profissional'),
        ),
    ]
