# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-15 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_projeto_profissionais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='created_date',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='created_date',
            new_name='data_criacao',
        ),
    ]
